### ISSUE TITLE
Add Coverage Badge

### ISSUE THREAD

**Issue by jannesrsa** [k2workflow/Chasm#33]
I'm a fan of the code coverage badge and I'm trying to implement it for this repository. I found that it gives a sense of accomplishment seeing that percentage increase.

I’ve run into some issues below and before I continue I would like to find out if this is something you would like and if so do you have other code coverage preferences or ideas on the issues.

I've created the following fork where I'm testing this out.
https://github.com/jannesrsa/Chasm

You'll see a codecov badge in the README.md and if you click on it, it will take you to https://codecov.io/gh/jannesrsa/Chasm, for a detailed view of the code coverage.

To get this far I had to make changes to the appveyor.ymll; due to challenges with .NET Core 2.0.

Currently the following is not working,

1) CI build does not fail on unit test failure
To get all the unit tests to execute, the tests need to run on the `SourceCode.Chasm.sln`. This causes errors where some of the projects don't have any tests to execute.
I’ve tried keeping the `test_script`, but it either only reports on the first test project to execute or fails.

2) NuGet publishing
I’m not sure if NuGet publishing is still working as expected. I had to remove the `donet pack` and add it to add `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` to the `.csproj`

3) Versioning
I’m not sure if the versions are correct. I’ve added to following to patch the version.

```
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%LABEL%'
package_version: '%LABEL%'
```

**Comment by grant-d** [comment]
Jannes this is a good idea, let's do it. @jcdickinson says he'll take a look at it a little later and let you know if there are any issues

**Comment by jcdickinson** [comment]
Your changes were a big help with getting this working.

1. I created a script that strips out non-test projects from the solution. Using the `--no-build` flag prevents another build from occurring (and likely failing, although I never tested to see if it would).
2. Nuget publishing works.
3. The `<Version>` and `<PackageVersion>` need to be in the project for the `dotnet_csproj` command to work.

Thanks for the contribution!

**Comment by jannesrsa** [comment]
Jonathan, I'm really happy you got this working! I was stuck with trying to get OpenCover and project builds working, so I'm happy the solution build ticked all the boxes.
