### ISSUE TITLE
TreeNodeList.IndexOf failing

### ISSUE THREAD

**Issue by grant-d** [k2workflow/Chasm#89]
https://github.com/k2workflow/Chasm/blob/935b243b5ec7cd157d8a949eca785f0a7ae27f23/src/SourceCode.Chasm.Tests/TreeNodeListTests.cs#L287

**Comment by jcdickinson** [comment]
This is not a bug, the correct assert is to check that it's less than 0. The return value of IndexOf when the item is not found is `TwosCompliment(Next Higher Item)`. This is used directly for the sorted insert.
