### ISSUE TITLE
PassThruCache Repository

### ISSUE THREAD

**Issue by jcdickinson** [k2workflow/Chasm#97]
A repository that contains a chain of other repositories that are used as a cache. 
- [ ] It shouldconform to the same `IChasmRepository` interface. As opposed to a different contract we need to support somehow.
- [ ] The hybrid/pipeline repo should do the right thing in both one-at-a-time and batch scenarios. For example, reading 20 blobs should fetch the (say) 10 cached ones locally, and the other 10 from remote storage.
- [ ] Reading from a remote repo should propagate the content to the local repo(s)
- [ ] Consider whether cache eviction is a feature we need here
- [ ] Consider whether 'in memory' is another kind of cache that could be chained
- [ ] CircuitBreaker semantics

**Comment by grant-d** [comment]
Closing due to archive
